global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - 'eureka-server:8761'
        - 'api-gateway:9000'
        - 'anggota-service:8087'
        - 'buku-service:8088'
        - 'peminjaman-service:8086'
        - 'pengembalian-service:8089'
